allowBuilds:
  '@openapitools/openapi-generator-cli': true
  esbuild: true
minimumReleaseAgeExclude:
  - globals@17.12.0
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@openapitools/openapi-generator-cli"
optimisticRepeatInstall: false
